In [55]:
import numpy as np
# import sys #Para ver o tamanho em bytes

### Criando 1° Array(Lista)

In [56]:
a = [1, 2, 3, 4, 5]

# Para criar um Array sempre tem que colocar os parêntes e dento dos Cocheites EX: 
b = np.array([1, 2, 3, 4, 5])

In [57]:
print(a)
print(b)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


A lista gasta mais moria que o Array.numpy.

In [58]:
# sys.getsizeof(a)

In [59]:
# b.nbytes

### Cirando Arrays em 1D, 2D e 3D

#### Array 1D

In [60]:
# Array 1D
d1 = np.array([1, 2, 3])

print(d1)

[1 2 3]


In [61]:
d1.shape

(3,)

In [62]:
d1.ndim

1

In [63]:
d1.dtype

dtype('int64')

#### Array 2D

In [64]:
# Array 2D
d2 = np.array([[1, 2, 3], [1, 2, 3]])

print(d2)

[[1 2 3]
 [1 2 3]]


In [65]:
d2.shape

(2, 3)

In [66]:
d2.ndim

2

In [67]:
d2.dtype

dtype('int64')

#### Array 3D

In [68]:
# Array 3D
d3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [69]:
d3.shape

(2, 2, 2)

In [70]:
d3.ndim

3

In [71]:
d3.dtype

dtype('int64')

### Somando daus Arrays

In [77]:
a = [2, 3, 4]
b = [2, 3, 4]

In [78]:
resultado = a + b

resultado

[2, 3, 4, 2, 3, 4]

In [74]:
a = np.array([2, 3, 4])
b = np.array([2, 3, 4])

In [76]:
resultado = np.add(a, b)

print(resultado)

[4 6 8]


### Selecionar intens do Array

In [80]:
a = np.array([[2, 3, 4, 5], [6, 7, 8, 9]])

print(a)

[[2 3 4 5]
 [6 7 8 9]]


Para selecioanr um intem: Passa os index EX:

Array [row, colu] (Linha e Coluna)

In [ ]:
a[1,2]

print(a[1,-2]) # Também pode fazer a contagem regreciva
print(a[1,2])

8
8


In [ ]:
# Para mostra só uma Row (Linha)

a[0,:] # 0 Linhas (Row) e : Todas a colunas

In [ ]:
# Para mostra as linhas e delimtaer as colunas

a[:, 1] # Vai mostrar todas alinhas da coluna 1

### Dicas de Numpy

Leia a Documetação e Pratique os Exemplos